title: Kenny Hwang
logo: /assets/img/logo.png
description: |
  Greetings! 
  Updates to come.
  is this even updating wtf
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
include: ['_pages', '_posts']